/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AIRPORTS_H_RPCGEN
#define _AIRPORTS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXLEN 255

typedef char *CityA;

typedef char *StateA;

typedef char *AirportA;

typedef struct airportData *airportList;

typedef struct Node *nodePtr;

struct placeDataA {
	CityA cityName;
	StateA stateCode;
	float lat;
	float lon;
};
typedef struct placeDataA placeDataA;

struct airportData {
	AirportA airportCode;
	AirportA airportName;
	float lat;
	float lon;
	float distance;
	airportList next;
};
typedef struct airportData airportData;

struct coordinatesA {
	float lat;
	float lon;
};
typedef struct coordinatesA coordinatesA;

struct Node {
	airportData airport;
	nodePtr left;
	nodePtr right;
};
typedef struct Node Node;

struct findair_ret {
	int err;
	union {
		airportList list;
	} findair_ret_u;
};
typedef struct findair_ret findair_ret;

#define AIRPORTSERVER 0x21103789
#define AIR_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FINDAIRPORT 1
extern  findair_ret * findairport_1(coordinatesA *, CLIENT *);
extern  findair_ret * findairport_1_svc(coordinatesA *, struct svc_req *);
extern int airportserver_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FINDAIRPORT 1
extern  findair_ret * findairport_1();
extern  findair_ret * findairport_1_svc();
extern int airportserver_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_CityA (XDR *, CityA*);
extern  bool_t xdr_StateA (XDR *, StateA*);
extern  bool_t xdr_AirportA (XDR *, AirportA*);
extern  bool_t xdr_airportList (XDR *, airportList*);
extern  bool_t xdr_nodePtr (XDR *, nodePtr*);
extern  bool_t xdr_placeDataA (XDR *, placeDataA*);
extern  bool_t xdr_airportData (XDR *, airportData*);
extern  bool_t xdr_coordinatesA (XDR *, coordinatesA*);
extern  bool_t xdr_Node (XDR *, Node*);
extern  bool_t xdr_findair_ret (XDR *, findair_ret*);

#else /* K&R C */
extern bool_t xdr_CityA ();
extern bool_t xdr_StateA ();
extern bool_t xdr_AirportA ();
extern bool_t xdr_airportList ();
extern bool_t xdr_nodePtr ();
extern bool_t xdr_placeDataA ();
extern bool_t xdr_airportData ();
extern bool_t xdr_coordinatesA ();
extern bool_t xdr_Node ();
extern bool_t xdr_findair_ret ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AIRPORTS_H_RPCGEN */
