/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "airports.h"

bool_t
xdr_CityA (XDR *xdrs, CityA *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_StateA (XDR *xdrs, StateA *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AirportA (XDR *xdrs, AirportA *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_airportList (XDR *xdrs, airportList *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct airportData), (xdrproc_t) xdr_airportData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodePtr (XDR *xdrs, nodePtr *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct Node), (xdrproc_t) xdr_Node))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_placeDataA (XDR *xdrs, placeDataA *objp)
{
	register int32_t *buf;

	 if (!xdr_CityA (xdrs, &objp->cityName))
		 return FALSE;
	 if (!xdr_StateA (xdrs, &objp->stateCode))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->lon))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_airportData (XDR *xdrs, airportData *objp)
{
	register int32_t *buf;

	 if (!xdr_AirportA (xdrs, &objp->airportCode))
		 return FALSE;
	 if (!xdr_AirportA (xdrs, &objp->airportName))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->lon))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->distance))
		 return FALSE;
	 if (!xdr_airportList (xdrs, &objp->next))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_coordinatesA (XDR *xdrs, coordinatesA *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->lon))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Node (XDR *xdrs, Node *objp)
{
	register int32_t *buf;

	 if (!xdr_airportData (xdrs, &objp->airport))
		 return FALSE;
	 if (!xdr_nodePtr (xdrs, &objp->left))
		 return FALSE;
	 if (!xdr_nodePtr (xdrs, &objp->right))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_findair_ret (XDR *xdrs, findair_ret *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_airportList (xdrs, &objp->findair_ret_u.list))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
