/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "places.h"


void placeserver_1(char *host, char *city, char *state)
{
	CLIENT *clnt;
	findplace_ret  *result_1;
	location  findplace_1_arg;
	aList al; 
	
	findplace_1_arg.cityName = city;
	findplace_1_arg.stateCode = state; 

#ifndef	DEBUG
	clnt = clnt_create (host, PLACESERVER, PLACE_VERS, "udp");

	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = findplace_1(&findplace_1_arg, clnt);

	if (result_1 == (findplace_ret *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	if (result_1->err == 1){
	  printf("%s\n","inputed prefix is too ambiguous");
	}else if (result_1->err == -1){
	  printf("%s\n","unable to find place");
	}else{

	  for(al = result_1->findplace_ret_u.list; al != NULL; al = al->next){
		printf("code=%s, location=%s, distance=%f miles\n", al->airportCode, al->airportName, al->distance); 
	  }
	}
	
#ifndef	DEBUG
	clnt_freeres (clnt,(xdrproc_t) xdr_findplace_ret,(char *)result_1); 
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;
	char *city;
	char *state; 
	
	if (argc < 4) {
		printf ("usage: %s server_host city state\n", argv[0]);
		exit (1);
	}

	
	host = argv[1];
	city = argv[2];
	state = argv[3]; 
	placeserver_1 (host,city,state);
	exit (0);
}
