/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PLACES_H_RPCGEN
#define _PLACES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXLEN 255

typedef char *City;

typedef char *State;

typedef char *Airport;

typedef struct aData *aList;

struct StateNode;
typedef struct StateNode StateNode;

struct AlphaNode;
typedef struct AlphaNode AlphaNode; 
  
struct placeData {
	City cityName;
	State stateCode;
	float lat;
	float lon;
};
typedef struct placeData placeData;

struct aData {
	Airport airportCode;
	Airport airportName;
	float lat;
	float lon;
	float distance;
	aList next;
};
typedef struct aData aData;

struct location {
	City cityName;
	State stateCode;
};
typedef struct location location;

struct coordinates {
	float lat;
	float lon;
};
typedef struct coordinates coordinates;

struct findplace_ret {
	int err;
	union {
		aList list;
	} findplace_ret_u;
};
typedef struct findplace_ret findplace_ret;

#define PLACESERVER 0x21103788
#define PLACE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FINDPLACE 1
extern  findplace_ret * findplace_1(location *, CLIENT *);
extern  findplace_ret * findplace_1_svc(location *, struct svc_req *);
extern int placeserver_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FINDPLACE 1
extern  findplace_ret * findplace_1();
extern  findplace_ret * findplace_1_svc();
extern int placeserver_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_City (XDR *, City*);
extern  bool_t xdr_State (XDR *, State*);
extern  bool_t xdr_Airport (XDR *, Airport*);
extern  bool_t xdr_aList (XDR *, aList*);
extern  bool_t xdr_placeData (XDR *, placeData*);
extern  bool_t xdr_aData (XDR *, aData*);
extern  bool_t xdr_location (XDR *, location*);
extern  bool_t xdr_coordinates (XDR *, coordinates*);
extern  bool_t xdr_findplace_ret (XDR *, findplace_ret*);

#else /* K&R C */
extern bool_t xdr_City ();
extern bool_t xdr_State ();
extern bool_t xdr_Airport ();
extern bool_t xdr_aList ();
extern bool_t xdr_placeData ();
extern bool_t xdr_aData ();
extern bool_t xdr_location ();
extern bool_t xdr_coordinates ();
extern bool_t xdr_findplace_ret ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PLACES_H_RPCGEN */
