/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "places.h"

bool_t
xdr_City (XDR *xdrs, City *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_State (XDR *xdrs, State *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Airport (XDR *xdrs, Airport *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_aList (XDR *xdrs, aList *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct aData), (xdrproc_t) xdr_aData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_placeData (XDR *xdrs, placeData *objp)
{
	register int32_t *buf;

	 if (!xdr_City (xdrs, &objp->cityName))
		 return FALSE;
	 if (!xdr_State (xdrs, &objp->stateCode))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->lon))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_aData (XDR *xdrs, aData *objp)
{
	register int32_t *buf;

	 if (!xdr_Airport (xdrs, &objp->airportCode))
		 return FALSE;
	 if (!xdr_Airport (xdrs, &objp->airportName))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->lon))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->distance))
		 return FALSE;
	 if (!xdr_aList (xdrs, &objp->next))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_location (XDR *xdrs, location *objp)
{
	register int32_t *buf;

	 if (!xdr_City (xdrs, &objp->cityName))
		 return FALSE;
	 if (!xdr_State (xdrs, &objp->stateCode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_coordinates (XDR *xdrs, coordinates *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->lon))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_findplace_ret (XDR *xdrs, findplace_ret *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_aList (xdrs, &objp->findplace_ret_u.list))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
